[default]
src = 'contracts'
test = 'contracts/test/foundry'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config